#include <qcommon/sys_console_internal.h>

#include <cerrno>
#include <cstddef>
#include <limits>

#include <poll.h>
#include <pthread.h>
#include <signal.h>
#include <sys/stat.h>
#include <unistd.h>

namespace
{
int OutputDescriptor(const SysConsoleOutputStream stream) noexcept
{
    return stream == SysConsoleOutputStream::StandardOutput
        ? STDOUT_FILENO
        : STDERR_FILENO;
}

// A pipe write with no reader both returns EPIPE and raises SIGPIPE.  Block it
// only on this thread while the write is in flight, then consume exactly the
// signal generated by this operation.  A signal that was already pending
// remains pending, and the caller's original mask is restored on every path.
class ScopedSigpipeBlock final
{
public:
    ScopedSigpipeBlock() noexcept
    {
        if (sigemptyset(&blocked_) != 0
            || sigaddset(&blocked_, SIGPIPE) != 0
            || pthread_sigmask(SIG_BLOCK, &blocked_, &previous_) != 0)
        {
            return;
        }
        active_ = true;

        sigset_t pending{};
        if (sigpending(&pending) != 0)
            return;
        const int membership = sigismember(&pending, SIGPIPE);
        if (membership < 0)
            return;
        pendingBefore_ = membership != 0;
        ready_ = true;
    }

    ScopedSigpipeBlock(const ScopedSigpipeBlock &) = delete;
    ScopedSigpipeBlock &operator=(const ScopedSigpipeBlock &) = delete;

    ~ScopedSigpipeBlock()
    {
        (void)restore();
    }

    [[nodiscard]] bool ready() const noexcept
    {
        return ready_;
    }

    [[nodiscard]] bool consumeGenerated(const int writeError) noexcept
    {
        if (writeError != EPIPE || pendingBefore_)
            return true;

        // POSIX permits an ignored blocked signal to be discarded instead of
        // queued.  Do not enter sigwait unless this write actually left a
        // SIGPIPE pending, or an inherited SIG_IGN disposition could hang the
        // error path forever.
        sigset_t pending{};
        if (sigpending(&pending) != 0)
            return false;
        const int membership = sigismember(&pending, SIGPIPE);
        if (membership < 0)
            return false;
        if (membership == 0)
            return true;

        int received = 0;
        int waitStatus = 0;
        do
        {
            waitStatus = sigwait(&blocked_, &received);
        } while (waitStatus == EINTR);
        return waitStatus == 0 && received == SIGPIPE;
    }

    [[nodiscard]] bool restore() noexcept
    {
        if (!active_)
            return true;
        if (pthread_sigmask(SIG_SETMASK, &previous_, nullptr) != 0)
            return false;
        active_ = false;
        return true;
    }

private:
    sigset_t blocked_{};
    sigset_t previous_{};
    bool active_ = false;
    bool ready_ = false;
    bool pendingBefore_ = false;
};
} // namespace

SysConsoleIoStatus Sys_ConsoleBackendWrite(
    const SysConsoleOutputStream stream,
    const char *bytes,
    std::size_t byteCount) noexcept
{
    const int descriptor = OutputDescriptor(stream);
    ScopedSigpipeBlock sigpipe;
    if (!sigpipe.ready())
        return SysConsoleIoStatus::IoError;

    while (byteCount != 0)
    {
        const std::size_t request = byteCount
                > static_cast<std::size_t>(
                    (std::numeric_limits<ssize_t>::max)())
            ? static_cast<std::size_t>(
                (std::numeric_limits<ssize_t>::max)())
            : byteCount;
        const ssize_t written = write(descriptor, bytes, request);
        if (written > 0)
        {
            bytes += written;
            byteCount -= static_cast<std::size_t>(written);
            continue;
        }
        if (written < 0 && errno == EINTR)
            continue;
        if (written == 0)
        {
            (void)sigpipe.restore();
            return SysConsoleIoStatus::IoError;
        }

        const int writeError = errno;
        const bool consumed = sigpipe.consumeGenerated(writeError);
        const bool restored = sigpipe.restore();
        if (!consumed || !restored)
            return SysConsoleIoStatus::IoError;
        return writeError == EBADF
            ? SysConsoleIoStatus::Unavailable
            : SysConsoleIoStatus::IoError;
    }
    return sigpipe.restore()
        ? SysConsoleIoStatus::Complete
        : SysConsoleIoStatus::IoError;
}

SysConsoleIoStatus Sys_ConsoleBackendFlush(
    const SysConsoleOutputStream stream) noexcept
{
    struct stat status{};
    return fstat(OutputDescriptor(stream), &status) == 0
        ? SysConsoleIoStatus::Complete
        : (errno == EBADF
            ? SysConsoleIoStatus::Unavailable
            : SysConsoleIoStatus::IoError);
}

bool Sys_ConsoleBackendIsRedirected(
    const SysConsoleOutputStream stream) noexcept
{
    const int descriptor = OutputDescriptor(stream);
    struct stat status{};
    return fstat(descriptor, &status) == 0 && isatty(descriptor) == 0;
}

SysConsoleRawReadResult Sys_ConsoleBackendTryReadByte() noexcept
{
    pollfd input{};
    input.fd = STDIN_FILENO;
    input.events = POLLIN | POLLHUP;

    int pollResult = 0;
    do
    {
        pollResult = poll(&input, 1, 0);
    } while (pollResult < 0 && errno == EINTR);

    if (pollResult == 0)
        return {SysConsoleRawReadStatus::NoData, 0};
    if (pollResult < 0 || (input.revents & POLLNVAL) != 0)
        return {SysConsoleRawReadStatus::IoError, 0};
    if ((input.revents & (POLLIN | POLLHUP)) == 0)
        return {SysConsoleRawReadStatus::IoError, 0};

    unsigned char byte = 0;
    ssize_t readCount = 0;
    do
    {
        readCount = read(STDIN_FILENO, &byte, 1);
    } while (readCount < 0 && errno == EINTR);

    if (readCount == 1)
        return {SysConsoleRawReadStatus::Data, byte};
    if (readCount == 0)
        return {SysConsoleRawReadStatus::EndOfFile, 0};
    if (errno == EAGAIN || errno == EWOULDBLOCK)
        return {SysConsoleRawReadStatus::NoData, 0};
    return {SysConsoleRawReadStatus::IoError, 0};
}
