cmake_minimum_required(VERSION 3.16)

# Exact sizeof-assert debt ledger for the M1/M4 ABI split. Direct literal
# assertions are keyed by path + assertion kind + whitespace-canonical expression
# + duplicate occurrence, so unrelated line movement is stable while weakening,
# type/size changes, additions, and removals are all visible. Formula-based
# assertions are kept in a separate exact ledger until they are classified as
# on-disk or runtime ABI. This is intentionally a fail-closed lexical inventory:
# assertions inside inactive preprocessor branches remain tracked as source debt.

if (NOT DEFINED SOURCE_ROOT OR NOT DEFINED ALLOWLIST OR NOT DEFINED FORMULA_ALLOWLIST)
    message(FATAL_ERROR "SOURCE_ROOT, ALLOWLIST, and FORMULA_ALLOWLIST are required")
endif()
if (NOT EXISTS "${ALLOWLIST}" OR NOT EXISTS "${FORMULA_ALLOWLIST}")
    message(FATAL_ERROR "ABI sizeof debt allowlists are required")
endif()

set(SRC_DIR "${SOURCE_ROOT}/src")
string(ASCII 9 _tab)
set(_excluded_regex
    "/physics/ode/|/groupvoice/speex/|/universal/kisak_abi\\.h$|/universal/layout_asserts\\.h$")
set(_comparison_regex
    "sizeof[ ]*\\([^|)]*\\)[ ]*==[ ]*(0[xX][0-9A-Fa-f]+|[0-9]+)")
set(_direct_regex "${_comparison_regex}[ ]*(\\)|,|&&|\\|\\|)")

function(canonicalize_whitespace INPUT OUTPUT)
    string(REPLACE " " "" _canonical "${INPUT}")
    string(REPLACE "${_tab}" "" _canonical "${_canonical}")
    set(${OUTPUT} "${_canonical}" PARENT_SCOPE)
endfunction()

function(mask_string_and_char_literals INPUT OUTPUT)
    string(LENGTH "${INPUT}" _length)
    set(_result "")
    set(_quote "")
    set(_escaped FALSE)
    set(_index 0)
    while(_index LESS _length)
        string(SUBSTRING "${INPUT}" ${_index} 1 _char)
        if (_quote STREQUAL "")
            if (_char STREQUAL "\"" OR _char STREQUAL "'")
                set(_quote "${_char}")
                string(APPEND _result " ")
            else()
                string(APPEND _result "${_char}")
            endif()
        else()
            string(APPEND _result " ")
            if (_escaped)
                set(_escaped FALSE)
            elseif(_char STREQUAL "\\")
                set(_escaped TRUE)
            elseif(_char STREQUAL "${_quote}")
                set(_quote "")
            endif()
        endif()
        math(EXPR _index "${_index} + 1")
    endwhile()
    set(${OUTPUT} "${_result}" PARENT_SCOPE)
endfunction()

function(strip_comments INPUT INITIAL_STATE OUTPUT FINAL_STATE)
    set(_remaining "${INPUT}")
    set(_result "")
    set(_in_comment "${INITIAL_STATE}")
    while(TRUE)
        if (_in_comment)
            string(FIND "${_remaining}" "*/" _comment_end)
            if (_comment_end EQUAL -1)
                set(_remaining "")
                break()
            endif()
            math(EXPR _after_comment "${_comment_end} + 2")
            string(SUBSTRING "${_remaining}" ${_after_comment} -1 _remaining)
            set(_in_comment FALSE)
        else()
            string(FIND "${_remaining}" "/*" _comment_start)
            string(FIND "${_remaining}" "//" _line_comment_start)
            if (NOT _line_comment_start EQUAL -1
                AND (_comment_start EQUAL -1 OR _line_comment_start LESS _comment_start))
                if (_line_comment_start GREATER 0)
                    string(SUBSTRING "${_remaining}" 0 ${_line_comment_start} _prefix)
                    string(APPEND _result "${_prefix}")
                endif()
                break()
            endif()
            if (_comment_start EQUAL -1)
                string(APPEND _result "${_remaining}")
                break()
            endif()
            if (_comment_start GREATER 0)
                string(SUBSTRING "${_remaining}" 0 ${_comment_start} _prefix)
                string(APPEND _result "${_prefix}")
            endif()
            math(EXPR _after_start "${_comment_start} + 2")
            string(SUBSTRING "${_remaining}" ${_after_start} -1 _remaining)
            set(_in_comment TRUE)
        endif()
    endwhile()
    set(${OUTPUT} "${_result}" PARENT_SCOPE)
    set(${FINAL_STATE} "${_in_comment}" PARENT_SCOPE)
endfunction()

function(append_occurrence BASE FOUND_BASES FOUND_ENTRIES)
    set(_bases "${${FOUND_BASES}}")
    set(_entries "${${FOUND_ENTRIES}}")
    set(_occurrence 1)
    foreach(_seen IN LISTS _bases)
        if (_seen STREQUAL "${BASE}")
            math(EXPR _occurrence "${_occurrence} + 1")
        endif()
    endforeach()
    list(APPEND _bases "${BASE}")
    list(APPEND _entries "${BASE}|${_occurrence}")
    set(${FOUND_BASES} "${_bases}" PARENT_SCOPE)
    set(${FOUND_ENTRIES} "${_entries}" PARENT_SCOPE)
endfunction()

function(read_allowlist PATH KIND OUTPUT)
    file(STRINGS "${PATH}" _lines)
    set(_entries)
    foreach(_raw_line IN LISTS _lines)
        string(STRIP "${_raw_line}" _line)
        if (_line STREQUAL "" OR _line MATCHES "^#")
            continue()
        endif()

        string(REGEX MATCHALL "\\|" _separators "${_line}")
        list(LENGTH _separators _separator_count)
        if (NOT _separator_count EQUAL 2
            OR NOT _line MATCHES "^[^|]+\\|[^|]+\\|[1-9][0-9]*$")
            message(FATAL_ERROR "Malformed ${KIND} ABI debt entry: ${_line}")
        endif()
        if (_line IN_LIST _entries)
            message(FATAL_ERROR "Duplicate ${KIND} ABI debt entry: ${_line}")
        endif()
        list(APPEND _entries "${_line}")
    endforeach()

    set(_sorted "${_entries}")
    list(SORT _sorted)
    if (NOT "${_entries}" STREQUAL "${_sorted}")
        message(FATAL_ERROR "${KIND} ABI debt allowlist must be sorted: ${PATH}")
    endif()
    set(${OUTPUT} "${_entries}" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE _sources
    "${SRC_DIR}/*.cpp"
    "${SRC_DIR}/*.h")
list(SORT _sources)

set(_direct_bases)
set(_direct_found)
set(_formula_bases)
set(_formula_found)
foreach(_source IN LISTS _sources)
    if (_source MATCHES "${_excluded_regex}")
        continue()
    endif()

    # CMake lists reinterpret semicolons, backslashes, and unmatched square
    # brackets. Encode those bytes before splitting the source into a list so
    # arbitrary C++ strings and array expressions cannot swallow nearby lines.
    file(READ "${_source}" _encoded_lines)
    set(_escape_prefix "__KISAK_ABI_SCAN_")
    if (_encoded_lines MATCHES "${_escape_prefix}")
        message(FATAL_ERROR "ABI scanner escape token occurs in ${_source}")
    endif()
    string(REPLACE "\\" "${_escape_prefix}BS__" _encoded_lines "${_encoded_lines}")
    string(REPLACE ";" "${_escape_prefix}SEMI__" _encoded_lines "${_encoded_lines}")
    string(REPLACE "[" "${_escape_prefix}LBR__" _encoded_lines "${_encoded_lines}")
    string(REPLACE "]" "${_escape_prefix}RBR__" _encoded_lines "${_encoded_lines}")
    string(REPLACE "\r" "" _encoded_lines "${_encoded_lines}")
    string(REPLACE "\n" ";" _encoded_lines "${_encoded_lines}")

    file(RELATIVE_PATH _rel "${SRC_DIR}" "${_source}")
    set(_assertion "")
    set(_assertion_kind "")
    set(_in_block_comment FALSE)
    foreach(_encoded_line IN LISTS _encoded_lines)
        string(REPLACE "${_escape_prefix}BS__" "\\" _line "${_encoded_line}")
        string(REPLACE "${_escape_prefix}SEMI__" ";" _line "${_line}")
        string(REPLACE "${_escape_prefix}LBR__" "[" _line "${_line}")
        string(REPLACE "${_escape_prefix}RBR__" "]" _line "${_line}")
        if (NOT _in_block_comment
            AND _assertion STREQUAL ""
            AND NOT _line MATCHES "(/\\*|\\*/|//|static_assert|iassert)")
            continue()
        endif()
        string(FIND "${_line}" "\"" _double_quote)
        string(FIND "${_line}" "'" _single_quote)
        if (NOT _double_quote EQUAL -1 OR NOT _single_quote EQUAL -1)
            mask_string_and_char_literals("${_line}" _line)
        endif()
        strip_comments("${_line}" "${_in_block_comment}" _line _in_block_comment)
        string(REPLACE "${_tab}" " " _line "${_line}")
        string(STRIP "${_line}" _line)
        if (_assertion STREQUAL "")
            if (_line MATCHES "^(#|//|/\\*|\\*)"
                OR NOT _line MATCHES "^(static_assert|iassert)[ ]*\\(")
                continue()
            endif()
            string(REGEX MATCH "^(static_assert|iassert)[ ]*\\(.*$" _assertion "${_line}")
            if (_assertion MATCHES "^static_assert")
                set(_assertion_kind "static_assert")
            else()
                set(_assertion_kind "iassert")
            endif()
        else()
            string(APPEND _assertion " ${_line}")
        endif()

        # Assertions may span physical lines. Wait for their statement terminator,
        # then inspect every direct comparison in the complete statement.
        if (NOT _assertion MATCHES ";")
            continue()
        endif()
        string(REPLACE ";" "" _scan_statement "${_assertion}")

        string(REGEX MATCHALL "${_direct_regex}" _direct_matches "${_scan_statement}")
        foreach(_direct_match IN LISTS _direct_matches)
            string(REGEX MATCH "${_comparison_regex}" _comparison "${_direct_match}")
            canonicalize_whitespace("${_comparison}" _canonical)
            append_occurrence(
                "${_rel}|${_assertion_kind}:${_canonical}"
                _direct_bases
                _direct_found)
        endforeach()

        string(REGEX MATCHALL "sizeof[ ]*\\(" _sizeof_tokens "${_scan_statement}")
        list(LENGTH _sizeof_tokens _sizeof_count)
        list(LENGTH _direct_matches _direct_count)
        if (_assertion_kind STREQUAL "static_assert" AND _sizeof_count GREATER _direct_count)
            canonicalize_whitespace("${_scan_statement}" _canonical_formula)
            string(REGEX REPLACE "^static_assert\\(" "" _canonical_formula "${_canonical_formula}")
            string(REGEX REPLACE "\\)$" "" _canonical_formula "${_canonical_formula}")
            append_occurrence(
                "${_rel}|${_canonical_formula}"
                _formula_bases
                _formula_found)
        endif()

        set(_assertion "")
        set(_assertion_kind "")
    endforeach()
    if (NOT _assertion STREQUAL "")
        message(FATAL_ERROR "Unterminated assertion while scanning ${_source}")
    endif()
    if (_in_block_comment)
        message(FATAL_ERROR "Unterminated block comment while scanning ${_source}")
    endif()
endforeach()
list(SORT _direct_found)
list(SORT _formula_found)

if (DEFINED DUMP_DIRECT AND DEFINED DUMP_FORMULA)
    string(REPLACE ";" "\n" _direct_text "${_direct_found}")
    string(REPLACE ";" "\n" _formula_text "${_formula_found}")
    file(WRITE "${DUMP_DIRECT}" "${_direct_text}\n")
    file(WRITE "${DUMP_FORMULA}" "${_formula_text}\n")
    return()
endif()

read_allowlist("${ALLOWLIST}" "direct-literal sizeof" _direct_allowed)
read_allowlist("${FORMULA_ALLOWLIST}" "formula sizeof" _formula_allowed)

function(compare_debt KIND FOUND ALLOWED)
    set(_found "${${FOUND}}")
    set(_allowed "${${ALLOWED}}")
    set(_new)
    set(_stale)
    foreach(_entry IN LISTS _found)
        if (NOT _entry IN_LIST _allowed)
            list(APPEND _new "${_entry}")
        endif()
    endforeach()
    foreach(_entry IN LISTS _allowed)
        if (NOT _entry IN_LIST _found)
            list(APPEND _stale "${_entry}")
        endif()
    endforeach()

    if (_new)
        message("New ${KIND} ABI debt (migrate to ONDISK_SIZE/RUNTIME_SIZE):")
        foreach(_entry IN LISTS _new)
            message("  ${_entry}")
        endforeach()
    endif()
    if (_stale)
        message("Stale ${KIND} ABI debt (remove the migrated/deleted entry):")
        foreach(_entry IN LISTS _stale)
            message("  ${_entry}")
        endforeach()
    endif()
    if (_new OR _stale)
        set(_debt_mismatch TRUE PARENT_SCOPE)
    endif()
endfunction()

set(_debt_mismatch FALSE)
compare_debt("direct-literal sizeof" _direct_found _direct_allowed)
compare_debt("formula sizeof" _formula_found _formula_allowed)
if (_debt_mismatch)
    message(FATAL_ERROR "Update or burn down the exact ABI sizeof debt ledgers")
endif()

list(LENGTH _direct_found _direct_count)
list(LENGTH _formula_found _formula_count)
message(STATUS
    "Tracked ${_direct_count} direct-literal and ${_formula_count} formula sizeof ABI assertions")
