# Compile current production declarations/bodies for the animation value migration.
kisakcod_renderer_enum_slice(bgame/bg_public.h "enum scriptAnimConditions_t" "\n};" anim_scriptAnimConditions_t)
kisakcod_renderer_enum_slice(bgame/bg_public.h "enum scriptAnimPerkStates_t" "\n};" anim_scriptAnimPerkStates_t)
kisakcod_renderer_enum_slice(bgame/bg_public.h "enum scriptAnimWeaponPositions_t" "\n};" anim_scriptAnimWeaponPositions_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum scriptAnimNoteType_t" "\n};" anim_scriptAnimNoteType_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum scriptAnimMoveTypes_t" "\n};" anim_scriptAnimMoveTypes_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum scriptAnimEventTypes_t" "\n};" anim_scriptAnimEventTypes_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum animBodyPart_t" "\n};" anim_animBodyPart_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum aistateEnum_t" "\n};" anim_aistateEnum_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum scriptAnimStrafeStates_t" "\n};" anim_scriptAnimStrafeStates_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum animScriptParseMode_t" "\n};" anim_animScriptParseMode_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum MantleAnims" "\n};" anim_MantleAnims)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum PlayerSpreadOverrideState" "\n};" anim_PlayerSpreadOverrideState)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum PmStanceFrontBack" "\n};" anim_PmStanceFrontBack)
kisakcod_renderer_enum_slice(bgame/bg_weapons.h "enum weapClass_t" "\n};" anim_weapClass_t)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct KISAK_ALIGNAS(8) animation_s" "\n};" animation_record)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct animScriptCondition_t" "\n};" animation_condition_record)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct animScriptCommand_t" "\n};" animation_command_record)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct animScriptItem_t" "\n};" animation_item_record)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct animScript_t" "\n};" animation_script_record)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct MantleAnimTransition" "\n};" mantle_transition_record)
kisakcod_renderer_enum_slice(bgame/bg_mantle.cpp "const MantleAnimTransition s_mantleTrans[" "\n};" mantle_transitions)
kisakcod_renderer_enum_slice(bgame/bg_mantle.cpp "int __cdecl Mantle_FindTransition(" "\n}" mantle_find_body)
kisakcod_renderer_enum_slice(bgame/bg_pmove.cpp "int32_t __cdecl PM_GetEffectiveStance(" "\n}" animation_stance_body)
kisakcod_renderer_enum_slice(bgame/bg_pmove.cpp "int32_t __cdecl PM_GetStanceEx(" "\n}" animation_stance_ex_body)
kisakcod_renderer_enum_slice(bgame/bg_weapons.cpp "void __cdecl BG_GetSpreadForWeapon(" "\n}" animation_spread_body)
kisakcod_renderer_enum_slice(bgame/bg_animation_mp.cpp "const char *__cdecl GetMoveTypeName(" "\n}" animation_move_name_body)
kisakcod_renderer_enum_slice(bgame/bg_animation_mp.cpp "void __cdecl BG_SetupAnimNoteTypes(" "\n}" animation_notes_body)
kisakcod_renderer_enum_slice(bgame/bg_animation_mp.cpp "int numDefines[" ";" animation_defines)
kisakcod_renderer_enum_slice(bgame/bg_animation_mp.cpp "memset(numDefines, 0, sizeof(numDefines))" ";" animation_clear_defines)
