# Reuse the existing fail-closed declaration/body extractor in the renderer gate.
kisakcod_renderer_enum_slice(bgame/bg_public.h "enum perksEnum" "\n};" gameplay_perk_enum)
kisakcod_renderer_enum_slice(game/game_public.h "enum DAMAGE_FLAGS" "\n};" gameplay_damage_enum)
kisakcod_renderer_enum_slice(game/g_local.h "enum meansOfDeath_t" "\n};" gameplay_mod_sp)
kisakcod_renderer_enum_slice(game_mp/g_public_mp.h "enum meansOfDeath_t" "\n};" gameplay_mod_mp)
kisakcod_renderer_enum_slice(bgame/bg_perks_mp.cpp "const char *bg_perkNames[" "\n};" gameplay_perk_names)
kisakcod_renderer_enum_slice(bgame/bg_perks_mp.cpp "uint32_t __cdecl BG_GetPerkIndexForName(" "\n}" gameplay_perk_lookup)
kisakcod_renderer_enum_slice(game_mp/g_client_script_cmd_mp.cpp "bool __cdecl IsBulletImpactMOD(" "\n}" gameplay_bullet_mod)
kisakcod_renderer_enum_slice(game_mp/g_vehicles_mp.cpp "bool __cdecl G_VehImmuneToDamage(" "\n}" gameplay_vehicle_immunity)

kisakcod_renderer_enum_slice(bgame/bg_weapons.h "enum weaponstate_t" "\n};" weapon_state_enum)
kisakcod_renderer_enum_slice(bgame/bg_weapons.h "enum weapAnimFiles_t" "\n};" weapon_file_enum)
kisakcod_renderer_enum_slice(bgame/bg_weapons.h "enum weapAnimNumber_t" "\n};" weapon_command_enum)
kisakcod_renderer_enum_slice(bgame/bg_weapons.cpp "int __cdecl PM_InteruptWeaponWithProneMove(" "\n}" weapon_prone_body)
kisakcod_renderer_enum_slice(cgame/cg_weapons.cpp "int32_t g_animRateOffsets[" "\n};" weapon_rate_offsets)
kisakcod_renderer_enum_slice(cgame/cg_weapons.cpp "double __cdecl GetWeaponAnimRate(" "\n}" weapon_rate_body)
kisakcod_renderer_enum_slice(cgame/cg_weapons.cpp "void __cdecl WeaponRunXModelAnims(" "\n}" weapon_run_anims_body)
kisakcod_renderer_enum_slice(xanim/xanim.h "const char* szXAnims[" ";" weapon_animation_slots)

# Entity, turret and geometry names preserve each profile's existing values.
kisakcod_renderer_enum_slice(bgame/bg_public.h "enum $A1BE347394FC01D8E43F73A65E725CFC" "\n};" turret_flags_enum)
kisakcod_renderer_enum_slice(qcommon/ent.h "#ifdef KISAK_MP\nenum entityType_t" "\n#endif" entity_type_enums)
kisakcod_renderer_enum_slice(../deps/ode/objects.h "enum PhysWorld" "\n};" physics_world_enum)
kisakcod_renderer_enum_slice(../deps/ode/collision.h "enum PhysicsGeomType" "\n};" physics_geom_enum)
kisakcod_renderer_enum_slice(physics/phys_ode.cpp "int __cdecl Phys_IndexFromODEWorld(" "\n}" physics_world_index_body)
kisakcod_renderer_enum_slice(game/g_scr_main.cpp "void __cdecl GScr_ValidateLightVis(" "\n}" entity_light_vis_body)
kisakcod_renderer_enum_slice(game/g_scr_main.cpp "void __cdecl GScr_SetMode(" "\n}" turret_mode_body)

# Compile all three migrated event-bound comparisons, including their signedness.
set(event_checks "using EventCheck = bool (*)(entityType_t);\nconstexpr EventCheck eventChecks[] = {\n")
foreach(source IN ITEMS cgame/cg_ents.cpp game/g_utils.cpp)
    set(source "${SRC_DIR}/${source}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
    file(READ "${source}" entity_text)
    string(REGEX MATCHALL "static_cast<uint32_t>\\([A-Za-z>.-]+eType\\) [<>]=? ET_EVENTS" expressions "${entity_text}")
    foreach(expression IN LISTS expressions)
        string(REGEX REPLACE "[A-Za-z>.-]+eType" "kind" expression "${expression}")
        string(APPEND event_checks "+[](entityType_t kind) { return ${expression}; },\n")
    endforeach()
endforeach()
string(APPEND event_checks "};\nstatic_assert(sizeof(eventChecks) / sizeof(eventChecks[0]) == 3);\n")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/renderer-enums/entity_event_checks.inc" "${event_checks}")

kisakcod_renderer_enum_slice(game/teams.h "enum team_t" "\n};" team_enum)
kisakcod_renderer_enum_slice(bgame/bg_local.h "enum objectiveState_t" "\n};" objective_enum)
kisakcod_renderer_enum_slice(bgame/bg_local.h "struct objective_t" "\n};" objective_record)
kisakcod_renderer_enum_slice(universal/q_shared.h "#define MAX_OBJECTIVES " "\n" objective_count)
kisakcod_renderer_enum_slice(client/client.h "    CS_OBJECTIVES " "\n" objective_cs_first)
kisakcod_renderer_enum_slice(client/client.h "    CS_OBJECTIVES_LAST " "\n" objective_cs_last)
kisakcod_renderer_enum_slice(cgame/cg_main.h "struct objectiveInfo_t" "\n};" objective_info_record)
kisakcod_renderer_enum_slice(cgame/cg_main.h "struct targetInfo_t" "\n};" objective_target_record)
kisakcod_renderer_enum_slice(cgame/cg_main.h "    objectiveInfo_t objectives[" "kMaxTargets];" objective_adjacent_arrays)
kisakcod_renderer_enum_slice(cgame_mp/cg_local_mp.h "    int32_t teamScores[" "teamPlayers[TEAM_NUM_TEAMS];" scoreboard_team_arrays)
kisakcod_renderer_enum_slice(cgame_mp/cg_scoreboard_mp.cpp "int32_t __cdecl CG_ScoreboardTotalLines(" "\n}" scoreboard_lines_body)
kisakcod_renderer_enum_slice(bgame/bg_local.h "    objective_t objective[" ";" player_objective_array)
kisakcod_renderer_enum_slice(game_mp/g_main_mp.h "    objective_t objectives[" ";" level_objective_array)
kisakcod_renderer_enum_slice(game_mp/g_main_mp.cpp "void __cdecl G_UpdateObjectiveToClients(" "\n}" objective_clients_body)

include("${CMAKE_CURRENT_LIST_DIR}/animation_value_contracts.cmake")

include("${CMAKE_CURRENT_LIST_DIR}/hint_value_contracts.cmake")
