set(SRC_DIR "${SOURCE_ROOT}/src")
set(DEPS_DIR "${SOURCE_ROOT}/deps")
set(SCRIPTS_DIR "${SOURCE_ROOT}/scripts")
set(KISAK_DEDI_HEADLESS ON)

include("${SCRIPTS_DIR}/common_files.cmake")
include("${SCRIPTS_DIR}/mp/mp_files.cmake")
include("${SCRIPTS_DIR}/dedi/dedi_files.cmake")
include("${SCRIPTS_DIR}/dedi/dedi_sources.cmake")

kisakcod_get_dedi_sources(_dedi_sources)

set(_debt_include_regex
    "^[ \t]*#[ \t]*include[ \t]*[<\\\"](\\.\\./)*(client|client_mp|cgame|cgame_mp|gfx_d3d|sound|ui|ui_mp|EffectsCore|DynEntity|devgui|groupvoice|bink|mss)(/|[>\\\"])"
)

function(kisakcod_headless_eval_condition DIRECTIVE OUT_KNOWN OUT_VALUE)
    set(_known FALSE)
    set(_value FALSE)

    if (DIRECTIVE MATCHES "^#[ \t]*ifdef[ \t]+KISAK_DEDI_HEADLESS([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value TRUE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*ifndef[ \t]+KISAK_DEDI_HEADLESS([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+defined\\([ \t]*KISAK_DEDI_HEADLESS[ \t]*\\)([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value TRUE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+![ \t]*defined\\([ \t]*KISAK_DEDI_HEADLESS[ \t]*\\)([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*ifdef[ \t]+KISAK_MP([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value TRUE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*ifndef[ \t]+KISAK_MP([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+KISAK_MP([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value TRUE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+defined\\([ \t]*KISAK_MP[ \t]*\\)([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value TRUE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*ifdef[ \t]+KISAK_SP([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*ifndef[ \t]+KISAK_SP([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value TRUE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+KISAK_SP([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+defined\\([ \t]*KISAK_SP[ \t]*\\)([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    elseif (DIRECTIVE MATCHES "^#[ \t]*(if|elif)[ \t]+defined\\([ \t]*KISAK_MP[ \t]*\\)[ \t]*&&[ \t]*![ \t]*defined\\([ \t]*KISAK_DEDI_HEADLESS[ \t]*\\)([ \t]*($|//|/\\*)|$)")
        set(_known TRUE)
        set(_value FALSE)
    endif()

    set(${OUT_KNOWN} "${_known}" PARENT_SCOPE)
    set(${OUT_VALUE} "${_value}" PARENT_SCOPE)
endfunction()

set(_found)
foreach(_source ${_dedi_sources})
    if (IS_DIRECTORY "${_source}" OR NOT EXISTS "${_source}")
        continue()
    endif()

    file(STRINGS "${_source}" _lines)
    set(_current_scan TRUE)
    set(_parent_scan_stack)
    set(_scan_stack)
    set(_condition_known_stack)
    set(_branch_taken_stack)
    foreach(_line ${_lines})
        string(STRIP "${_line}" _stripped)

        if (_stripped MATCHES "^#[ \t]*(if|ifdef|ifndef)([ \t(]|$)")
            kisakcod_headless_eval_condition("${_stripped}" _condition_known _condition_value)
            set(_parent_scan "${_current_scan}")
            set(_branch_scan "${_parent_scan}")
            set(_branch_taken FALSE)
            if (_condition_known)
                if (_parent_scan AND _condition_value)
                    set(_branch_scan TRUE)
                else()
                    set(_branch_scan FALSE)
                endif()
                set(_branch_taken "${_condition_value}")
            endif()
            list(APPEND _parent_scan_stack "${_parent_scan}")
            list(APPEND _scan_stack "${_branch_scan}")
            list(APPEND _condition_known_stack "${_condition_known}")
            list(APPEND _branch_taken_stack "${_branch_taken}")
            set(_current_scan "${_branch_scan}")
            continue()
        endif()

        if (_stripped MATCHES "^#[ \t]*elif([ \t(]|$)")
            list(LENGTH _scan_stack _stack_length)
            if (_stack_length EQUAL 0)
                continue()
            endif()
            math(EXPR _top_index "${_stack_length} - 1")
            list(GET _parent_scan_stack ${_top_index} _parent_scan)
            list(GET _condition_known_stack ${_top_index} _condition_known)
            list(GET _branch_taken_stack ${_top_index} _branch_taken)

            kisakcod_headless_eval_condition("${_stripped}" _elif_known _elif_value)
            set(_branch_scan FALSE)
            set(_new_branch_taken "${_branch_taken}")
            if (_condition_known)
                if (NOT _branch_taken)
                    if (_elif_known)
                        if (_parent_scan AND _elif_value)
                            set(_branch_scan TRUE)
                        endif()
                        if (_elif_value)
                            set(_new_branch_taken TRUE)
                        endif()
                    elseif (_parent_scan)
                        set(_branch_scan TRUE)
                    endif()
                endif()
            else()
                if (_parent_scan AND (NOT _elif_known OR _elif_value))
                    set(_branch_scan TRUE)
                endif()
            endif()

            list(REMOVE_AT _scan_stack ${_top_index})
            list(APPEND _scan_stack "${_branch_scan}")
            list(REMOVE_AT _branch_taken_stack ${_top_index})
            list(APPEND _branch_taken_stack "${_new_branch_taken}")
            set(_current_scan "${_branch_scan}")
            continue()
        endif()

        if (_stripped MATCHES "^#[ \t]*else([ \t(]|$)")
            list(LENGTH _scan_stack _stack_length)
            if (_stack_length EQUAL 0)
                continue()
            endif()
            math(EXPR _top_index "${_stack_length} - 1")
            list(GET _parent_scan_stack ${_top_index} _parent_scan)
            list(GET _condition_known_stack ${_top_index} _condition_known)
            list(GET _branch_taken_stack ${_top_index} _branch_taken)

            set(_branch_scan "${_parent_scan}")
            if (_condition_known AND _branch_taken)
                set(_branch_scan FALSE)
            endif()

            list(REMOVE_AT _scan_stack ${_top_index})
            list(APPEND _scan_stack "${_branch_scan}")
            list(REMOVE_AT _branch_taken_stack ${_top_index})
            list(APPEND _branch_taken_stack TRUE)
            set(_current_scan "${_branch_scan}")
            continue()
        endif()

        if (_stripped MATCHES "^#[ \t]*endif([ \t]*($|//|/\\*)|$)")
            list(LENGTH _scan_stack _stack_length)
            if (_stack_length GREATER 0)
                math(EXPR _top_index "${_stack_length} - 1")
                list(REMOVE_AT _parent_scan_stack ${_top_index})
                list(REMOVE_AT _scan_stack ${_top_index})
                list(REMOVE_AT _condition_known_stack ${_top_index})
                list(REMOVE_AT _branch_taken_stack ${_top_index})
            endif()

            list(LENGTH _scan_stack _stack_length)
            if (_stack_length GREATER 0)
                math(EXPR _top_index "${_stack_length} - 1")
                list(GET _scan_stack ${_top_index} _current_scan)
            else()
                set(_current_scan TRUE)
            endif()
            continue()
        endif()

        if (NOT _current_scan)
            continue()
        endif()

        if (NOT _line MATCHES "${_debt_include_regex}")
            continue()
        endif()

        file(RELATIVE_PATH _rel "${SRC_DIR}" "${_source}")
        string(STRIP "${_line}" _include)
        list(APPEND _found "${_rel}|${_include}")
    endforeach()
endforeach()
list(SORT _found)

set(_allowed)
file(STRINGS "${ALLOWLIST}" _allowlist_lines)
foreach(_line ${_allowlist_lines})
    string(STRIP "${_line}" _line)
    if (_line STREQUAL "" OR _line MATCHES "^#")
        continue()
    endif()
    list(APPEND _allowed "${_line}")
endforeach()
list(SORT _allowed)

set(_new_debt)
foreach(_entry ${_found})
    if (NOT _entry IN_LIST _allowed)
        list(APPEND _new_debt "${_entry}")
    endif()
endforeach()

set(_stale_debt)
foreach(_entry ${_allowed})
    if (NOT _entry IN_LIST _found)
        list(APPEND _stale_debt "${_entry}")
    endif()
endforeach()

if (_new_debt OR _stale_debt)
    if (_new_debt)
        message("New headless client/media include debt:")
        foreach(_entry ${_new_debt})
            message("  ${_entry}")
        endforeach()
    endif()
    if (_stale_debt)
        message("Stale headless client/media include debt allowlist entries:")
        foreach(_entry ${_stale_debt})
            message("  ${_entry}")
        endforeach()
    endif()
    message(FATAL_ERROR "Update or burn down tests/headless_include_debt.allow")
endif()

list(LENGTH _found _debt_count)
message(STATUS "Tracked ${_debt_count} direct client/media includes in the headless dedicated source profile")
