# Reuse the fail-closed production slice helper from renderer_enum_contracts.cmake.
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "enum GfxImageFileFormat" "\n};" image_format_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "enum file_image_flags_t" "\n};" image_flags_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "enum $E681A048096CB9E4B36F1590F98F8E52" "\n};" image_category_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "enum $1B8EAFF1434832E143B04F7E036A82BD" "\n};" image_semantic_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "enum GfxRefBlendMode" "\n};" image_blend_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "struct GfxImageFileHeader" "\n};" image_file_header)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "struct GfxRawPixel" "\n};" image_raw_pixel)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "struct GfxRawImage" "\n};" image_raw_record)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "enum MapType" "\n};" image_map_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "struct Picmip" "\n};" image_picmip_type)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "struct CardMemory" "\n};" image_memory_type)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "union GfxTexture" "\n};" image_texture_type)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "struct GfxImage //" "\n};" image_record)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.h "inline uint32_t __cdecl Image_GetUsage(" "\n}" image_usage_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.cpp "uint32_t __cdecl Image_CountMipmaps(" "\n}" image_mip_count_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_image_load_obj.cpp "void __cdecl Image_LoadFromData(" "\n}" image_dispatch_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_imagedecode.cpp "void __cdecl Image_CopyBitmapData(" "\n}" image_bitmap_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_image_load_common.cpp "void __cdecl Image_PicmipForSemantic(" "\n}" image_picmip_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.cpp "void __cdecl R_FreeLostImage(" "\n}" image_release_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_image.cpp "void __cdecl R_RebuildLostImage(" "\n}" image_recovery_body)
