# Extract current production declarations/bodies; fail closed if a boundary moves.
function(kisakcod_renderer_enum_slice source begin end name)
    set(source "${SRC_DIR}/${source}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
    file(READ "${source}" text)
    string(FIND "${text}" "${begin}" first)
    string(FIND "${text}" "${begin}" last_start REVERSE)
    if(first LESS 0 OR NOT first EQUAL last_start)
        message(FATAL_ERROR "Missing/ambiguous renderer contract start: ${begin}")
    endif()
    string(SUBSTRING "${text}" ${first} -1 body)
    string(FIND "${body}" "${end}" last)
    if(last LESS 1)
        message(FATAL_ERROR "Missing renderer contract end: ${end}")
    endif()
    string(LENGTH "${end}" end_length)
    math(EXPR length "${last} + ${end_length}")
    string(SUBSTRING "${body}" 0 ${length} body)
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/renderer-enums/${name}.inc" "${body}\n")
endfunction()
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/renderer-enums")
kisakcod_renderer_enum_slice(gfx_d3d/r_dvars.h "enum GfxAspectRatio" "\n};" aspect_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_primarylights.h "enum GfxLightType" "\n};" light_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "enum GfxDepthRangeType" "\n};" depth_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_rendercmds.h "enum GfxStencilOp" "\n};" stencil_op_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_rendercmds.h "enum GfxStencilFunc" "\n};" stencil_func_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_init.h "struct GfxWindowParms" "\n};" window_type)
kisakcod_renderer_enum_slice(gfx_d3d/r_rendercmds.h "struct StateBitsTable" "\n};" state_bits_type)
kisakcod_renderer_enum_slice(gfx_d3d/rb_logfile.h "struct StencilLogBits" "\n};" stencil_type)
kisakcod_renderer_enum_slice(gfx_d3d/r_init.cpp "void __cdecl R_StoreWindowSettings(" "\n}" aspect_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_light.cpp "bool __cdecl R_LightImportanceGreaterEqual(" "\n}" light_body)
kisakcod_renderer_enum_slice(gfx_d3d/rb_logfile.cpp "void __cdecl RB_LogStencilState(" "\n}" stencil_body)

# Compile the actual RHS from all 15 migrated draw/prepass sites. Only replace
# the context field with the test input; do not duplicate the selector logic.
set(selectors "using DepthSelector = GfxDepthRangeType (*)(int);\nconstexpr DepthSelector depthSelectors[] = {\n")
foreach(source IN ITEMS rb_backend.cpp rb_tess.cpp)
    set(source "${SRC_DIR}/gfx_d3d/${source}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
    file(READ "${source}" text)
    string(REGEX MATCHALL "[A-Za-z]+\\.source->cameraView[ \t]*[?][^;\n]*" expressions "${text}")
    foreach(expression IN LISTS expressions)
        string(REGEX REPLACE "[A-Za-z]+\\.source->cameraView" "cameraView" expression "${expression}")
        string(APPEND selectors "+[](int cameraView) { return ${expression}; },\n")
    endforeach()
endforeach()
string(APPEND selectors "};\nstatic_assert(sizeof(depthSelectors) / sizeof(depthSelectors[0]) == 15);\n")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/renderer-enums/depth_selectors.inc" "${selectors}")
