# Compile current production declarations and bodies in the renderer contract gate.
kisakcod_renderer_enum_slice(gfx_d3d/r_state.h "enum CodeConstant" "\n};" code_constants)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "enum MaterialTechniqueType" "\n};" technique_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "enum $74254F2FBB58A9D84A85080F50CF363D" "\n};" shader_arg_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "enum MaterialTextureSource" "\n};" texture_source)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct MaterialArgumentCodeConst" "\n};" argument_code)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "union MaterialArgumentDef" "\n};" argument_union)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct MaterialShaderArgument" "\n};" shader_argument)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct MaterialPass //" "\n};" material_pass)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct MaterialConstantDef //" "\n};" material_constant)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "struct GfxDrawSurfFields" "\n};" draw_surf_fields)
kisakcod_renderer_enum_slice(gfx_d3d/r_gfx.h "union GfxDrawSurf //" "\n};" draw_surf)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct MaterialInfo //" "\n};" material_info)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct MaterialTechniqueSet //" "\n};" technique_set)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct Material //" "\n};" material_record)
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "struct GfxShaderConstantBlock" "\n};" shader_constant_block)
kisakcod_renderer_enum_slice(gfx_d3d/r_state_utils.cpp "void __cdecl R_SetGameTime(" "\n}" game_time_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_material_load_obj.cpp "int __cdecl Material_TechniqueTypeForName(" "\n}" technique_lookup_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_material_load_obj.cpp "void __cdecl R_RegisterShaderConst(" "\n}" shader_register_body)
kisakcod_renderer_enum_slice(gfx_d3d/r_material_load_obj.cpp "void __cdecl R_GetPixelLiteralConsts(" "\n}" pixel_literals_body)

# Exercise both actual shader-kind selectors introduced by the naming refactor.
set(shader_source "${SRC_DIR}/gfx_d3d/r_material_load_obj.cpp")
file(READ "${shader_source}" shader_text)
string(REGEX MATCHALL "argSource->type = shaderType == MTL_VERTEX_SHADER [^;\n]*" shader_expressions "${shader_text}")
set(shader_selectors "constexpr int MTL_VERTEX_SHADER = 0;\nusing ShaderSelector = int (*)(int);\nconstexpr ShaderSelector shaderSelectors[] = {\n")
foreach(expression IN LISTS shader_expressions)
    string(REPLACE "argSource->type = " "" expression "${expression}")
    string(APPEND shader_selectors "+[](int shaderType) -> int { return ${expression}; },\n")
endforeach()
string(APPEND shader_selectors "};\nstatic_assert(sizeof(shaderSelectors) / sizeof(shaderSelectors[0]) == 2);\n")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/renderer-enums/shader_selectors.inc" "${shader_selectors}")

# Surface names share the material declaration boundary, but retain native streams.
kisakcod_renderer_enum_slice(gfx_d3d/r_material.h "enum surfaceType_t" "\n};" surface_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_draw_method.h "enum GfxDrawSceneMethod" "\n};" draw_scene_enum)
kisakcod_renderer_enum_slice(gfx_d3d/r_draw_method.h "struct GfxDrawMethod" "\n};" draw_method_record)
kisakcod_renderer_enum_slice(gfx_d3d/r_draw_method.cpp "void __cdecl R_ForceLitTechType(" "\n}" force_lit_body)
