# Compile unchanged production bodies with service doubles. Source dependencies
# force regeneration after edits; missing boundaries fail configuration.
function(kisakcod_upstream_slice source begin end name)
    set(source "${SRC_DIR}/${source}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
    file(READ "${source}" text)
    string(FIND "${text}" "${begin}" first)
    if(first LESS 0)
        message(FATAL_ERROR "Missing upstream regression start: ${begin}")
    endif()
    string(SUBSTRING "${text}" ${first} -1 body)
    string(FIND "${body}" "${end}" last)
    if(last LESS 1)
        message(FATAL_ERROR "Missing upstream regression end: ${end}")
    endif()
    string(SUBSTRING "${body}" 0 ${last} body)
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/upstream-b3199/${name}.inc" "${body}\n")
endfunction()
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/upstream-b3199")
kisakcod_upstream_slice(bgame/bg_animation_mp.cpp "void __cdecl BG_LerpOffset(" "void __cdecl BG_Player_DoControllersSetup(" offset)
kisakcod_upstream_slice(gfx_d3d/rb_tess.cpp "void __cdecl RB_CreateParticleCloud2dAxis(" "uint32_t __cdecl R_TessXModelSkinnedDrawSurfList(" particle)
kisakcod_upstream_slice(bgame/bg_weapons.cpp "void __cdecl PM_Weapon_FinishWeaponChange(" "bool __cdecl PM_WeaponClipEmpty(" weapon)
kisakcod_upstream_slice(cgame_mp/cg_local_mp.h "struct score_t" "struct cg_s" score_type)
kisakcod_upstream_slice(cgame_mp/cg_servercmds_mp.cpp "void __cdecl CG_SortSingleClientScore(" "void __cdecl CG_ConfigStringModified(" score)
kisakcod_upstream_slice(client/client.h "struct MessageLine" "// cl_console" console_types)
kisakcod_upstream_slice(client/client.h "enum print_msg_dest_t" "inline print_msg_dest_t" console_dest)
kisakcod_upstream_slice(client/cl_console.cpp "void __cdecl Con_TimeJumped(" "void __cdecl Con_ResetMessageWindowTimes(" console_jump)
kisakcod_upstream_slice(client/cl_console.cpp "void __cdecl Con_TimeNudged(" "#endif" console_nudge)
kisakcod_upstream_slice(client/cl_console.cpp "void __cdecl Con_ClearNotify(" "void __cdecl Con_CheckResize(" console_clear)
kisakcod_upstream_slice(client/cl_console.cpp "MessageWindow *__cdecl Con_GetDestWindow(" "void __cdecl Con_UpdateNotifyLine(" console_get)
kisakcod_upstream_slice(client/cl_console.cpp "void __cdecl Con_ClearMiniConsole(" "void __cdecl Con_DrawErrors(" console_mini)
kisakcod_upstream_slice(client/cl_console.cpp "bool __cdecl Con_IsGameMessageWindowActive(" "void __cdecl Con_DrawSay(" console_active)
