// Voice codec parity gates (VOX-1a, docs/AUDIO_VOICE_CINEMATIC_PARITY_GATES.md
// Section 4.2) against the in-tree Speex 1.1.9 build that ships with the game
// (src/groupvoice/speex/*.c, public headers deps/speex/).
//
// This translation unit pins the golden encoder bitstreams byte-exactly and
// exercises the encode-side contracts; the decode-side contracts live in
// tests/voice_gate_decode_test.cpp and the shared production call sequences
// in tests/voice_gate_test_support.hpp (the suite is split across
// translation units to keep each analyzed file well under the
// static-analysis file-size limit).
//
// The production wrappers src/groupvoice/encode.cpp / decode.cpp are pinned to
// the 32-bit Win32 ABI by directsound.h struct static_asserts and therefore
// cannot run on portable CI targets. This suite instead drives the exact
// production call sequences (verified statement-for-statement by
// tests/voice_framing_source_test.cmake); see voice_gate_test_support.hpp
// for the pinned init/sample sequences.
//
// VOX-1a pins the encoder bitstream byte-exactly. Any byte difference on any
// target is a real gate failure: fork clients that disagree on encoder bytes
// could not interoperate with each other, and a codec substitution would
// change the bytes outright. The vectors are generated from this in-tree
// Speex 1.1.9 build (never retail/captured); regenerate with
//   ./kisakcod-voice-gate-tests --dump-goldens
// and paste the output into the kGoldens table below, recording the commit
// used for generation in the provenance comment. Provenance: the encode
// vectors are byte-identical to the original VOX-1a recording; the nb decode
// reference was regenerated in the same commit that replaced the decoder
// noise-synthesis PRNG (libc rand() -> per-decoder fixed-point LCG in
// misc.c, the CWE-327 repair), which changes receiver-local synthesis but
// no wire bytes.
//
// VOX-1b pins the decoder PCM within an explicit recorded tolerance
// (kDecodeTolerance, voice_gate_decode_test.cpp): a lossy codec is NOT
// asserted bit-exact against its input and NOT asserted exact against retail
// (Section 5 of the gates doc).

#include "voice_gate_test_support.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

namespace voice_gate
{
// Golden streams (VOX-1a): encoder bitstreams byte-for-byte, generated by
// --dump-goldens on this in-tree Speex 1.1.9 build. See the provenance note
// in voice_gate_test_support.hpp. Defined here (single copy across the
// suite); declared extern in voice_gate_test_support.hpp.
const char *kGoldenNbHex =
    "185489600039ce70001ce73808293a0e07689d091e8d2bf3dc3b30742e3e9aa61d2991257db20ea00e8cec693fee1afef5800039ce70201ce73810204fd0b334a63e1fd6d1e75939cd70af1ce73bff2bfb4e3ffb7a5718d949d1f8c7fa68fa5acfcb47aaabf21cc739ce";
const char *kGoldenWbHex =
    "185489500039ce70001ce738082e0200070fd95893bf9492061e997de4f22b3074c93e93a21f36bce9095b16ed9380002526";

const char *kGoldenNbDecodeHex =
    "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a10175029903a40476055c058504d002550099fd83fa22f800f678f55ff576f7eff9bcfd5304a607060d3e1004127410780d1907500071f81ef16eebabe715e7bae8b0edb1f348fc32043a0c90152519b61e7e1c25191a11fd07c6fba4f125e835e1b6de1cdff4e369ebb6f543006c0c8d174a202d27d5275a25891d20126503a5f4c0e5ced9d0d1e0ce2bd12ada8ce63ff6bc07b1193e285d3280370c36ad2eee21220b18f585e227d87ed741decaeb0bfae207d615dc1dd622cd218c21da16b1111007f4057bfe00fa01efe0f391f39dda4ed3e5e2cce93cee6101131460236c2a112aa0280422be12f303fef827ef90d5b2cc9ecb8bd443e132f3c3069d165822ac26e03b733aab3493263318df0372f079e157d524d26cce3be421dbe1d5aef72dfbfb0b501713229b22ea3c6b3611318c239d10f9fbfae829db63d27cd58aff680f72153e0dd40273f2f2e8c5e852eba7f2990b0df168d4d0064612d80b470c9e0fb010be063d07d3f8a10df8fe1c0415f086ff2f287cc709cca10b360696d67a0d0714c70c630853035e051c087e0462f31c0156f690f866f078f3af1f4bde83ec77e2161730f7b41e9effa6fd152c2b07e2fbeae8f1fd8310ecef39cddd03150e7c0f0efd380272067a15b521d9290131212b2f216e0e0b01fcf488f4c4fa31dde4e1f3f4ba1fb4e7120b0ee7830687e94be329f1e6f163f970259a0a4c19cf13e11f3c217a24cde7bc06bbf159f41b192bfc75ef50005f16c723832119186c0baa17110820f469e9fbdbde0c58f193f1641395dd39e8b61c6d1077fd6911e6071d2a17dff1e6490667eb930357cf96148fee3ee2d3eed91bf1087fea52fb99e7290aa9eca0f90af4c5207cfc87fa20f2e7dd2eeaec01ec0d90e4f5f85512dff76400d9e8b3f195faa2248cdefd18caf2881af81cf42619ee6f26b11b1c22c9fecf030c1032ea66e90ad5e913c01173ec71dd6be7bb18aaf5330730087ced2a31baea4dff9413971839274a2900ec690124d8eff819e6db1dee01870fade334fccd0f24e203010ed90eeba12894004e322efe1f14e31886f330fb03fc29d2d10e07e11de40919ac008c09e31669cfcf35ebf87217eb0a05fd2c1630ebc9ef54f341f20b0b4c085bff9406f4ff06075f01dc028205d60179fc85fe71ff5b0288034100a00139005bffe3fd2fff37009e023803d701c1ff22ff32000500e4ffe8ffdeff88005300d9ffc4ffc3ff030026000b00fefff3fff5ff0600030002000200010003000100fefffeffffff0000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007500b101250318052f065306cc041102ecfeecfc2e00db0384064604bcfe84f901f773f85ffb5bfe6ffde8fa52f8d0f81afd2e03a708f10a010ad306330323ff3efcc6f884f603f548f6e5f987ff1704bd0aa811df142010830466f799ed22ece1f00af9ab05590fbe14da10390549f7a9ecd6ea76f067faad0b5111f0101a0410f5c6eb3deb13f53701390c81122c0d5b02d2f317ef63f7eb02170c510cd5051bfdb2f8f0f9b9fe60032101ecfea0fb16fcc2fe73013a038f023e02da00dc02da048f06ea05740288f09ef19a04bd0e170d0cfe84f2e0effffa2307dc0d770b99048efe83fe21fc20fb57f8a6f825fcf1000205e304be032003110230007efb24fd00027e03de0059fdc3fcdcfe8a009b029501f30071001801a2012000cbfe49fd91fddbfe3e00fb00fb0008017f011502e7001bfd4bfef50212042a0172fd3111c6142729b718551e0614ad1a4f15ee06ddfd6dd893c7bfb442bfe9cbd4e60c07ef21d3424752bc413c3e6c469a251cf206d015c3b3c232d0b6dc24e224fa4c16be30d52f412eff222b1e25391f2691e720cca8bef6c029ba0fc653d0aaf145240d426b585d5439410e4408506c2d10dff6b691b7a0bbecce5ac1e9acebe5022ca74469335a3cfa3d4d547367d12a6ce863d189bedeaceea1aab006ba4dcd112e34438d5b484ac848bf46cf4e5c2c8dc5f5a5cc95d3a875b0b4adaaab6bef0745745de55f81589653a95aff5385244ccfebbba1a735a778b3b6ca23c9c1e1b93b644c09540a421a36712f583de62089bba4aaf9ae9ab900bdfec379c72e03775426672f5ecb4d1d3eda3b3f380e18d8b1efb5b1b55bbf24c85bd96bc796d4b033a1417c4ee73f8934872dd44b9f2bbdba50ae02ab7fb62cbddbc44abbbcf8902e5332d325181d7e0a9d06190d9afe24df9cea0ef020016bfb5de82ceb22fbd31f001a041aad0ac8fcfdfc3d077a0a0002680355f1e7e9b0ea5cf256fe46118418d210cf0cbef9ebf28fef74fe5ffe260ba70ef607b8055ff7fbf06ff14b050c13cd1705099af1bae5ebe5c6f69109d31ade1a5c15c4002df19de99ff52501e211ac13cf077ffe2eeef4e7e9ed990238176b2114141df9b6e7aae310f3d109";

void test_mode_geometry()
{
    for (int bandwidth_enum = 0; bandwidth_enum <= 2; ++bandwidth_enum)
    {
        Encoder enc;
        check(encoder_open(enc, bandwidth_enum, kProductionSamplerate, 1),
              "encoder opens for every production bandwidth enum");
        const int expected = (bandwidth_enum == 0) ? kFrameNb
                            : (bandwidth_enum == 1) ? kFrameWb
                                                    : kFrameUwb;
        check(enc.frame_size == expected, "GET_FRAME_SIZE matches mode geometry");
        encoder_close(enc);
    }
}

void test_golden_streams()
{
    const GoldenStream goldens[] = {
        {0, kProductionSamplerate, kShippedVoiceQuality, kGoldenNbHex},
        {1, 16000, kShippedVoiceQuality, kGoldenWbHex},
    };
    for (const GoldenStream &golden : goldens)
    {
        const auto frames = (golden.bandwidth_enum == 0) ? nb_stream_frames()
                                                         : wb_stream_frames();
        const std::vector<char> bytes =
            encode_stream(golden.bandwidth_enum, golden.samplerate, golden.quality, frames);
        check(!bytes.empty(), "encoder produced bytes for every frame");
        check(to_hex(bytes) == golden.hex,
              "VOX-1a: encoder bitstream is byte-identical to the pinned vector");
    }
}

// FINDING (recorded in the gates doc, Section 6): the ultra-wideband mode of
// this in-tree Speex 1.1.9 snapshot is not usable for encoding. Encoder init
// succeeds and reports the 640-sample frame geometry, but speex_encode_int
// faults inside the stacked subband encoder (sb_celp) regardless of VAD/DTX
// on the x86-64 gcc/glibc probe build. Production never reaches this path:
// win_voice.cpp:609 pins g_current_bandwidth_setting to 0 (narrowband) and
// win_voice.cpp:613 encodes exclusively through Encode_Init(0). The gate
// therefore pins nb (the shipped path) and wb byte-exactly, asserts only uwb
// init/geometry, and treats any uwb encode enablement as a change that must
// re-open this gate with fresh native-runtime evidence.
void test_uwb_init_only()
{
    // The gate stops at init/geometry for uwb: see the FINDING note above.
    Encoder enc;
    check(encoder_open(enc, 2, 32000, kShippedVoiceQuality),
          "uwb encoder init reports success");
    check(enc.frame_size == kFrameUwb, "uwb frame geometry is 640 samples");
    encoder_close(enc);
}

void test_determinism_and_state()
{
    const auto frames = nb_stream_frames();

    // Determinism: a fresh encoder reproduces the exact same stream.
    const std::vector<char> again =
        encode_stream(0, kProductionSamplerate, kShippedVoiceQuality, frames);
    check(to_hex(again) == kGoldenNbHex, "VOX-1a: encoding is deterministic across runs");

    // Statefulness: the chirp frame's bytes inside the sequential stream
    // differ from a fresh-encoder encode of the same frame.
    Encoder fresh;
    encoder_open(fresh, 0, kProductionSamplerate, kShippedVoiceQuality);
    char solo[2048];
    const int solo_len = encode_frame(fresh, frames[3].data(), solo, sizeof(solo));
    encoder_close(fresh);

    Encoder seq;
    encoder_open(seq, 0, kProductionSamplerate, kShippedVoiceQuality);
    char buffer[2048];
    int offset = 0;
    for (int i = 0; i <= 3; ++i)
    {
        const int n = encode_frame(seq, frames[i].data(), buffer, sizeof(buffer));
        if (i == 3)
        {
            check(n == solo_len, "frame length independent of encoder history");
            check(std::memcmp(buffer, solo, n) != 0,
                  "sequential encode differs from fresh encode (encoder state is on the wire)");
        }
        offset += n;
    }
    encoder_close(seq);
    (void)offset;
}

void test_quality_sensitivity()
{
    std::vector<int16_t> frame(kFrameNb, 0);
    fill_sine(frame.data(), kFrameNb, 440, 8000, 12000);
    const std::vector<char> q1 = encode_stream(0, kProductionSamplerate, 1, {frame});
    const std::vector<char> q3 = encode_stream(0, kProductionSamplerate, kShippedVoiceQuality, {frame});
    check(q1 != q3, "sv_voiceQuality changes the wire bytes (Encode_Sample sync is observable)");
}

void dump_goldens()
{
    const auto dump = [](const char *id, int bandwidth_enum, int samplerate, int quality,
                         const std::vector<std::vector<int16_t>> &frames) {
        const std::vector<char> bytes = encode_stream(bandwidth_enum, samplerate, quality, frames);
        std::printf("const char *kGolden%sHex =\n    \"", id);
        std::fputs(to_hex(bytes).c_str(), stdout);
        std::printf("\";\n");
        if (bandwidth_enum == 0)
        {
            std::vector<int> lengths;
            const std::vector<char> encoded =
                encode_stream(bandwidth_enum, samplerate, quality, frames, &lengths);
            Decoder dec;
            decoder_open(dec, 0, samplerate);
            const std::vector<int16_t> pcm = decode_stream(encoded, lengths, dec);
            decoder_close(dec);
            std::vector<char> pcm_bytes(pcm.size() * sizeof(int16_t));
            // Explicit little-endian byte stores: the reference format is
            // int16 LE (provenance note in voice_gate_test_support.hpp).
            // Indexed stores keep the destination bound explicit (CWE-120)
            // and pin the byte order independently of the host endianness.
            for (size_t i = 0; i < pcm.size(); ++i)
            {
                const uint16_t u = static_cast<uint16_t>(pcm[i]);
                pcm_bytes[2 * i] = static_cast<char>(u & 0xFFu);
                pcm_bytes[2 * i + 1] = static_cast<char>((u >> 8) & 0xFFu);
            }
            std::printf("const char *kGolden%sDecodeHex =\n    \"", id);
            std::fputs(to_hex(pcm_bytes).c_str(), stdout);
            std::printf("\";\n");
        }
    };
    dump("Nb", 0, kProductionSamplerate, kShippedVoiceQuality, nb_stream_frames());
    dump("Wb", 1, 16000, kShippedVoiceQuality, wb_stream_frames());
}
} // namespace voice_gate

int main(int argc, char **argv)
{
    if (argc == 2 && std::strcmp(argv[1], "--dump-goldens") == 0)
    {
        voice_gate::dump_goldens();
        return 0;
    }

    using namespace voice_gate;
    test_mode_geometry();
    test_golden_streams();
    test_uwb_init_only();
    test_determinism_and_state();
    test_quality_sensitivity();
    test_decode_golden();
    test_corrupt_decode_rejected();
    test_round_trip_lossy_not_bitexact();

    if (fail_count != 0)
    {
        std::fprintf(stderr, "%d voice codec gate check(s) failed\n", fail_count);
        return 1;
    }
    std::printf("voice codec gate contracts passed\n");
    return 0;
}
