// Voice codec parity gates (VOX-1a, docs/AUDIO_VOICE_CINEMATIC_PARITY_GATES.md
// Section 4.2) against the in-tree Speex 1.1.9 build that ships with the game
// (src/groupvoice/speex/*.c, public headers deps/speex/).
//
// This translation unit pins the golden encoder bitstreams byte-exactly and
// exercises the encode-side contracts; the decode-side contracts live in
// tests/voice_gate_decode_test.cpp and the shared production call sequences
// in tests/voice_gate_test_support.hpp (the suite is split across
// translation units to keep each analyzed file well under the
// static-analysis file-size limit).
//
// The production wrappers src/groupvoice/encode.cpp / decode.cpp are pinned to
// the 32-bit Win32 ABI by directsound.h struct static_asserts and therefore
// cannot run on portable CI targets. This suite instead drives the exact
// production call sequences (verified statement-for-statement by
// tests/voice_framing_source_test.cmake); see voice_gate_test_support.hpp
// for the pinned init/sample sequences.
//
// VOX-1a pins the encoder bitstream byte-exactly. Any byte difference on any
// target is a real gate failure: fork clients that disagree on encoder bytes
// could not interoperate with each other, and a codec substitution would
// change the bytes outright. The vectors are generated from this in-tree
// Speex 1.1.9 build (never retail/captured); regenerate with
//   ./kisakcod-voice-gate-tests --dump-goldens
// and paste the output into the kGoldens table below, recording the commit
// used for generation in the provenance comment. Provenance: the encode
// vectors are byte-identical to the original VOX-1a recording; the nb decode
// reference was regenerated in the same commit that replaced the decoder
// noise-synthesis PRNG (libc rand() -> per-decoder fixed-point LCG in
// misc.c, the CWE-327 repair), which changes receiver-local synthesis but
// no wire bytes.
//
// VOX-1b pins the decoder PCM within an explicit recorded tolerance
// (kDecodeTolerance, voice_gate_decode_test.cpp): a lossy codec is NOT
// asserted bit-exact against its input and NOT asserted exact against retail
// (Section 5 of the gates doc).

#include "voice_gate_test_support.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

namespace voice_gate
{
// Golden streams (VOX-1a): encoder bitstreams byte-for-byte, generated by
// --dump-goldens on this in-tree Speex 1.1.9 build. See the provenance note
// in voice_gate_test_support.hpp. Defined here (single copy across the
// suite); declared extern in voice_gate_test_support.hpp.
const char *kGoldenNbHex =
    "185489600039ce70001ce7380829fa2c07a483601e8d2bf2924c6ecb99149fe00b699111a7b0c2a00e8cec693fee19a9f5a00039ce70401ce739f8e74a524738dacd1fd6d1f26339ce71bc9ce73a2f2bfb6c3dfb7bb218d949d1f4c74268fa4c0a2847a880120264714f";
const char *kGoldenWbHex =
    "185489500039ce70001ce738082e02000704095893bf9492061e997de2922b3614b93e93a0ef36bcf1095b16ed9380002526";

const char *kGoldenNbDecodeHex =
    "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a10175029903a40476055c058504d002550099fd21f90df537f12bee5fecafec0cef8bf3cff90c01db086d0fac14ab16f315b611560b0203b3faa2f277e8cbe50ee3fee3eee75cef90f76301ea0919118f18ac1ac4199715930ecb04c5faa5f1f3e54edf7edc64dc5fe047e993f42a02950f081ba3247129af2818239918c30a41fc9bed04e0c0d4a8d08ad078d5d4df5dee44ffa8104420d32c0135bf36fd32e025f10f3cf775e50fd430d30ed88dc862ec87fcbff9c61417123b278524881c3221d0177612e0017efd57f428f2ebe956e8aee721ea6befcbf3effcfa075e13aa1eff25902ee229f6271f17f80e76fcc9e152dc1acc54d812cabbe6f9ec15f7f9feab038c268f2ba62b6e261d1d1b0a40f55ae6dadd71de99ce71c751c9b0d076db4def8406721ca42d6e357c347a2bc41e74102cffabf4ddf940e635cd00dac3025af5d8098a0b98f6e1eb9bd657e248eb0af4d9113bfa8de3a209d80f9a1e2c246b16e310210a4203ccf358fb39f086fb9ef67ffa411f7de3adf66c0613f635ebe2f477f04cdbece22be6abfdb006cb201bee5421caefa4f0d5fd6c0cb00a7ffa2deac3eb1a1587107414f4d53ced5e2b2d208b01bfef67f7132120f923d21d06be0b8b100eff9f003a002912c718b21610209f22c523f51cbe0eb90252ff1c0333e418e8dcf7ea1e41e6fc08e9e4a5047be79ae134f067f129f97e25c60aa219361435207f21af24f2e7d106c1f152f410191efc67ef43005516c0237f2117186b0bab17130823f46ce9fddbe00c59f193f1651395dd39e8b61c6c1076fd6911e5071d2a17dff1e6490667eb930357cf96148fee3ee2d3eed91bf1087fea52fb99e7290aa9eca0f90af4c5207cfc87fa20f2e7dd2eeaec01ec0d90e4f5f85512dff76400d9e8b3f195faa2248cdefd18caf2881af81cf42619ee6f26b11b1c22c9fecf030c1032ea66e90ad5e913c01173ec71dd6be7bb18aaf5330730087ced2a31baea4dff9413971839274a2900ec690124d8eff819e6db1dee01870fade334fccd0f24e203010ed90eeba12894004e322efe1f14e31886f330fb03fc29d2d10e07e11de40919ac008c09e31669cfcf35ebf87217eb0a05fd2c1630eb09e7abf82cfcfbfa4f0c37f9d2f571039405a1040e05d9ff040abd0370f56afd91fb65fec1fc1afc16010bfe9dfb43017a0344007d00bafddefe8700cffec4feda00b4007c003500effe96ff2c00c8ff12000300d9ff30002b00e5ff0f000c00f7ff0e00fdffedff04000100f9ff0200fffffdff05000100feff02000000000001000000ffff00000000000000000000000000000000000000000000000000004405be052c00a5ff59ff0000ea012c01dc068d045f044a08610269fcd3fab3f902faecfb44fc60fc7f07e90dcd06e7ff19fcb7faf8fb87fc7bfa7bfa3707340ece066aff38fb61fa4dfcbcfc52fa52fa5b0ccd0e77f47af29bfed1fce900bc0609020e00fbf773f7c104ae0cd20254f897fc2f04d305550327f2e3eedb034a116404bef688fb7204f707020630f92df84c0e861116f57eef34fbbb00f101bdfd97f8f4fc6b0357040003c70526028c0092025801eefb38fb51fedbfc65ff35069d01810091028302c2feb9fd93fffffc9dfd320273fd0bfa2d004e00befdc005b9025f032904fa0359040f01380033fe3704dafef6fc1d01bcffaaffa8fef9ff5401b8fc22020fff27ffdbfff5002b0187fe7e011302aafc490190fedaffecfe47010601fbfdf0013f0143fe7a00310216ff63ffe3032ffb40011afedcff9cfeab195c1e2127db1897167518e613760ecaf7cff5acd56bc0c9b9f8c266d834f2fa16052c324305522d2cb12c4b42d51775d7e1cb27d7eed087da9ce525ae80d407162e2f6324f525b6324e25ea2ead132cb3f1b5b3b435ba0aa2e9bbffd27ff91a3c10481a5a86541e4d32364641223386dc20af04b396c045b468ae8fb4e4b14b18b23e6035e233fd407f509b4e5e2a22bbc7bd5ec387b3c38e0d95cab6f8e3c7547b50465f8b543753b23a2043a2360ac24a9a2c9cebbb9aad55c04cb61fbb943adb5832505539944965321044382462a664b349b685b66a93cfb2cdb83ef21664035fa05efb4daa460c225740fc3757b708a2bc9b91c904bd22e732c628c6a84aae5a4159d83bb74c9720b04bbb355eb91eca9abc88bbd4988cbeb0b036edff5a805792583244b72831164037c934b0c18da9379f7fc612c298e065c09fbeb210961dd52ef813841490eb0101faff4bea1c0259fcd9fc29ee33ff71e947f8501a0e15480edf02b7011afada0c6d0dc7ffdcff74f82dff0af567f438f5cdfd5d052d08a50f5a04e8ffaaf629f09ff2d5fc4c068e0504002df855ec06edd7fd230ada11fb15480ba2feb4f141e740f58e00f40fa010960d91f550ef9de138eb4fff100fbc11990e5107e1f408e966e362f3330c4d1dcf18db0439f192e767ea";

void test_mode_geometry()
{
    for (int bandwidth_enum = 0; bandwidth_enum <= 2; ++bandwidth_enum)
    {
        Encoder enc;
        check(encoder_open(enc, bandwidth_enum, kProductionSamplerate, 1),
              "encoder opens for every production bandwidth enum");
        const int expected = (bandwidth_enum == 0) ? kFrameNb
                            : (bandwidth_enum == 1) ? kFrameWb
                                                    : kFrameUwb;
        check(enc.frame_size == expected, "GET_FRAME_SIZE matches mode geometry");
        encoder_close(enc);
    }
}

void test_golden_streams()
{
    const GoldenStream goldens[] = {
        {0, kProductionSamplerate, kShippedVoiceQuality, kGoldenNbHex},
        {1, 16000, kShippedVoiceQuality, kGoldenWbHex},
    };
    for (const GoldenStream &golden : goldens)
    {
        const auto frames = (golden.bandwidth_enum == 0) ? nb_stream_frames()
                                                         : wb_stream_frames();
        const std::vector<char> bytes =
            encode_stream(golden.bandwidth_enum, golden.samplerate, golden.quality, frames);
        check(!bytes.empty(), "encoder produced bytes for every frame");
        check(to_hex(bytes) == golden.hex,
              "VOX-1a: encoder bitstream is byte-identical to the pinned vector");
    }
}

// FINDING (recorded in the gates doc, Section 6): the ultra-wideband mode of
// this in-tree Speex 1.1.9 snapshot is not usable for encoding. Encoder init
// succeeds and reports the 640-sample frame geometry, but speex_encode_int
// faults inside the stacked subband encoder (sb_celp) regardless of VAD/DTX
// on the x86-64 gcc/glibc probe build. Production never reaches this path:
// win_voice.cpp:609 pins g_current_bandwidth_setting to 0 (narrowband) and
// win_voice.cpp:613 encodes exclusively through Encode_Init(0). The gate
// therefore pins nb (the shipped path) and wb byte-exactly, asserts only uwb
// init/geometry, and treats any uwb encode enablement as a change that must
// re-open this gate with fresh native-runtime evidence.
void test_uwb_init_only()
{
    // The gate stops at init/geometry for uwb: see the FINDING note above.
    Encoder enc;
    check(encoder_open(enc, 2, 32000, kShippedVoiceQuality),
          "uwb encoder init reports success");
    check(enc.frame_size == kFrameUwb, "uwb frame geometry is 640 samples");
    encoder_close(enc);
}

void test_determinism_and_state()
{
    const auto frames = nb_stream_frames();

    // Determinism: a fresh encoder reproduces the exact same stream.
    const std::vector<char> again =
        encode_stream(0, kProductionSamplerate, kShippedVoiceQuality, frames);
    check(to_hex(again) == kGoldenNbHex, "VOX-1a: encoding is deterministic across runs");

    // Statefulness: the chirp frame's bytes inside the sequential stream
    // differ from a fresh-encoder encode of the same frame.
    Encoder fresh;
    encoder_open(fresh, 0, kProductionSamplerate, kShippedVoiceQuality);
    char solo[2048];
    const int solo_len = encode_frame(fresh, frames[3].data(), solo, sizeof(solo));
    encoder_close(fresh);

    Encoder seq;
    encoder_open(seq, 0, kProductionSamplerate, kShippedVoiceQuality);
    char buffer[2048];
    int offset = 0;
    for (int i = 0; i <= 3; ++i)
    {
        const int n = encode_frame(seq, frames[i].data(), buffer, sizeof(buffer));
        if (i == 3)
        {
            check(n == solo_len, "frame length independent of encoder history");
            check(std::memcmp(buffer, solo, n) != 0,
                  "sequential encode differs from fresh encode (encoder state is on the wire)");
        }
        offset += n;
    }
    encoder_close(seq);
    (void)offset;
}

void test_quality_sensitivity()
{
    std::vector<int16_t> frame(kFrameNb, 0);
    fill_sine(frame.data(), kFrameNb, 440.0f, 8000.0f, 12000.0f);
    const std::vector<char> q1 = encode_stream(0, kProductionSamplerate, 1, {frame});
    const std::vector<char> q3 = encode_stream(0, kProductionSamplerate, kShippedVoiceQuality, {frame});
    check(q1 != q3, "sv_voiceQuality changes the wire bytes (Encode_Sample sync is observable)");
}

void dump_goldens()
{
    const auto dump = [](const char *id, int bandwidth_enum, int samplerate, int quality,
                         const std::vector<std::vector<int16_t>> &frames) {
        const std::vector<char> bytes = encode_stream(bandwidth_enum, samplerate, quality, frames);
        std::printf("static const char *kGolden%sHex =\n    \"", id);
        std::fputs(to_hex(bytes).c_str(), stdout);
        std::printf("\";\n");
        if (bandwidth_enum == 0)
        {
            std::vector<int> lengths;
            const std::vector<char> encoded =
                encode_stream(bandwidth_enum, samplerate, quality, frames, &lengths);
            Decoder dec;
            decoder_open(dec, 0, samplerate);
            const std::vector<int16_t> pcm = decode_stream(encoded, lengths, dec);
            decoder_close(dec);
            std::vector<char> pcm_bytes(pcm.size() * sizeof(int16_t));
            // Explicit little-endian byte stores: the reference format is
            // int16 LE (provenance note in voice_gate_test_support.hpp).
            // Indexed stores keep the destination bound explicit (CWE-120)
            // and pin the byte order independently of the host endianness.
            for (size_t i = 0; i < pcm.size(); ++i)
            {
                const uint16_t u = static_cast<uint16_t>(pcm[i]);
                pcm_bytes[2 * i] = static_cast<char>(u & 0xFFu);
                pcm_bytes[2 * i + 1] = static_cast<char>((u >> 8) & 0xFFu);
            }
            std::printf("static const char *kGolden%sDecodeHex =\n    \"", id);
            std::fputs(to_hex(pcm_bytes).c_str(), stdout);
            std::printf("\";\n");
        }
    };
    dump("Nb", 0, kProductionSamplerate, kShippedVoiceQuality, nb_stream_frames());
    dump("Wb", 1, 16000, kShippedVoiceQuality, wb_stream_frames());
}
} // namespace voice_gate

int main(int argc, char **argv)
{
    if (argc == 2 && std::strcmp(argv[1], "--dump-goldens") == 0)
    {
        voice_gate::dump_goldens();
        return 0;
    }

    using namespace voice_gate;
    test_mode_geometry();
    test_golden_streams();
    test_uwb_init_only();
    test_determinism_and_state();
    test_quality_sensitivity();
    test_decode_golden();
    test_corrupt_decode_rejected();
    test_round_trip_lossy_not_bitexact();

    if (fail_count != 0)
    {
        std::fprintf(stderr, "%d voice codec gate check(s) failed\n", fail_count);
        return 1;
    }
    std::printf("voice codec gate contracts passed\n");
    return 0;
}
