#pragma once

#include <universal/kisak_abi.h>

#if defined(KISAK_MP)
enum CriticalSection : std::int32_t
{
	CRITSECT_CONSOLE = 0x0,
	CRITSECT_DEBUG_SOCKET = 0x1,
	CRITSECT_COM_ERROR = 0x2,
	CRITSECT_STATMON = 0x3,
	CRITSECT_DEBUG_LINE = 0x4,
	CRITSECT_ALLOC_MARK = 0x5,
	CRITSECT_SCRIPT_STRING = 0x6,
	CRITSECT_MEMORY_TREE = 0x7,
	CRITSECT_ASSERT = 0x8,
	CRITSECT_RD_BUFFER = 0x9,
	CRITSECT_SYS_EVENT_QUEUE = 0xA,
	CRITSECT_GPU_FENCE = 0xB,
	CRITSECT_FATAL_ERROR = 0xC,
	CRITSECT_SCRIPT_DEBUGGER_ALLOC = 0xD,
	CRITSECT_MISSING_ASSET = 0xE,
	CRITSECT_PHYSICS = 0xF,
	CRITSECT_LIVE = 0x10,
	CRITSECT_AUDIO_PHYSICS = 0x11,
	CRITSECT_CINEMATIC = 0x12,
	CRITSECT_CINEMATIC_TARGET_CHANGE = 0x13,
	CRITSECT_FX_ALLOC = 0x14,
	CRITSECT_CBUF = 0x15,
	CRITSECT_DB_SCRIPT_STRING_TRANSACTION = 0x16,

	CRITSECT_COUNT = 0x17,
};
#elif defined(KISAK_SP)
enum CriticalSection : std::int32_t
{
	CRITSECT_CONSOLE = 0x0,
	CRITSECT_DEBUG_SOCKET = 0x1,
	CRITSECT_COM_ERROR = 0x2,
	CRITSECT_STATMON = 0x3,
	CRITSECT_SOUND_ALLOC = 0x4,
	CRITSECT_MEM_ALLOC0 = 0x5,
	CRITSECT_MEM_ALLOC1 = 0x6,
	CRITSECT_DEBUG_LINE = 0x7,
	CRITSECT_ALLOC_MARK = 0x8,
	CRITSECT_STREAMED_SOUND = 0x9,
	CRITSECT_FAKELAG = 0xA,
	CRITSECT_CLIENT_MESSAGE = 0xB,
	CRITSECT_CLIENT_CMD = 0xC,
	CRITSECT_DOBJ_ALLOC = 0xD,
	CRITSECT_START_SERVER = 0xE,
	CRITSECT_XANIM_ALLOC = 0xF,
	CRITSECT_KEY_BINDINGS = 0x10,
	CRITSECT_FX_VIS = 0x11,
	CRITSECT_SERVER_MESSAGE = 0x12,
	CRITSECT_SCRIPT_STRING = 0x13,
	CRITSECT_MEMORY_TREE = 0x14,
	CRITSECT_ASSERT = 0x15,
	CRITSECT_SCRIPT_DEBUGGER_ALLOC = 0x16,
	CRITSECT_MISSING_ASSET = 0x17,
	CRITSECT_PHYSICS = 0x18,
	CRITSECT_LIVE = 0x19,
	CRITSECT_AUDIO_PHYSICS = 0x1A,
	CRITSECT_CINEMATIC = 0x1B,
	CRITSECT_CINEMATIC_TARGET_CHANGE = 0x1C,
	CRITSECT_FX_ALLOC = 0x1D,
	CRITSECT_NETTHREAD_OVERRIDE = 0x1E,
	CRITSECT_CBUF = 0x1F,

	// LWSS ADD
	CRITSECT_SYS_EVENT_QUEUE,
	CRITSECT_FATAL_ERROR,
	CRITSECT_GPU_FENCE,
	// LWSS END
	CRITSECT_DB_SCRIPT_STRING_TRANSACTION,

	CRITSECT_COUNT,
};
#endif

struct FastCriticalSection
{
	volatile std::uint32_t readCount;
	volatile std::uint32_t writeCount;
};

RUNTIME_SIZE(FastCriticalSection, 8, 8);

void KISAK_CDECL Sys_InitializeCriticalSections();
void KISAK_CDECL Sys_EnterCriticalSection(int critSect);
void KISAK_CDECL Sys_LeaveCriticalSection(int critSect);
void KISAK_CDECL Sys_LockRead(FastCriticalSection *critSect);
void KISAK_CDECL Sys_UnlockRead(FastCriticalSection *critSect);
void KISAK_CDECL Sys_LockWrite(FastCriticalSection *critSect);
void KISAK_CDECL Sys_UnlockWrite(FastCriticalSection *critSect);
bool KISAK_CDECL Sys_IsWriteLocked(const FastCriticalSection *critSect);
