#!/usr/bin/env python3
"""Generate the disk32 mirror structs from src/database/db_disk32.schema."""

# A retail fast-file stores each record in its 32-bit (ILP32) layout
# (docs/design/FASTFILE_LOADER.md). For every schema record this emits the
# disk32 mirror struct (pointer fields are 4-byte disk32::Ptr32 tokens) with
# ONDISK_SIZE/ONDISK_OFFSET asserts on the declared retail values, and
# RUNTIME_SIZE/RUNTIME_OFFSET asserts on the native struct the mirror converts
# into, computed from the same field list, so a native struct that drifts from
# its schema stops the build. Declared offsets that break the ILP32 layout
# rules fail here. The output is a build artifact, never committed (AGENTS.md
# rule 8).

import sys
from pathlib import Path

# kind: (mirror type, native size and alignment at ILP32, at 64-bit)
KINDS = {
    'i32': ('std::int32_t', 4, 4),
    'u32': ('std::uint32_t', 4, 4),
    'f32': ('float', 4, 4),
    'u8': ('std::uint8_t', 1, 1),
    'bool': ('std::uint8_t', 1, 1),  # any disk byte; the loader tests != 0
    'xstring': ('Ptr32<const char>', 4, 8),
    'bytes': ('Ptr32<const char>', 4, 8),
    'xstrings': ('Ptr32<Ptr32<const char>>', 4, 8),
}
COUNTED = ('bytes', 'xstrings')


def fail(where, message):
    sys.exit(f'{where}: {message}')


def parse_record(words, where):
    attrs = dict(word.split('=', 1) for word in words[3:] if '=' in word)
    if len(words) < 3 or len(attrs) != len(words) - 3 \
            or not {'runtime', 'header'} <= attrs.keys() <= {'runtime', 'header', 'same'}:
        fail(where, 'expected: record <Name> <size> runtime=<type> header=<path> [same=<constant>]')
    return {'name': words[1], 'size': int(words[2], 0), 'fields': [], 'where': where, **attrs}


def parse_field(words, where):
    count = words[3] if len(words) == 4 else ''
    if len(words) not in (3, 4) or words[2] not in KINDS or (words[2] in COUNTED) != count.startswith('count='):
        fail(where, f'expected: <offset> <field> <kind> [count=<expression> for {COUNTED}]; kinds {sorted(KINDS)}')
    return int(words[0], 0), words[1], words[2], count[len('count='):]


def parse(path):
    records = []
    for number, raw in enumerate(path.read_text().splitlines(), 1):
        where, words = f'{path}:{number}', raw.split('#', 1)[0].split()
        if words and words[0] == 'record':
            records.append(parse_record(words, where))
        elif words and not records:
            fail(where, 'a field must follow a record line')
        elif words:
            records[-1]['fields'].append(parse_field(words, where))
    return records


def layout(fields, width):
    """Natural-alignment offsets and size; width 1 is ILP32, 2 is 64-bit."""
    offsets, offset, biggest = [], 0, 1
    for _, _, kind, _ in fields:
        size = KINDS[kind][width]
        offset = (offset + size - 1) // size * size
        offsets.append(offset)
        offset += size
        biggest = max(biggest, size)
    return offsets, (offset + biggest - 1) // biggest * biggest


def emit(records, schema_name):
    out = [f'// Generated by scripts/gen_disk32.py from {schema_name}. Do not edit;',
           '// it is rebuilt from the schema and never committed (AGENTS.md rule 8).',
           '#pragma once', '', '#include <database/db_disk32.h>', '#include <universal/kisak_abi.h>']
    out += [f'#include <{header}>' for header in sorted({record['header'] for record in records})]
    out += ['', '#include <cstddef>', '#include <cstdint>', '#include <type_traits>', '', 'namespace disk32', '{']
    for record in records:
        mirror = record['name'] + 'Disk32'
        out += [f'// Retail {record["name"]}: 0x{record["size"]:02X} bytes.', f'struct {mirror}', '{']
        out += [f'    {KINDS[kind][0]} {field};' + (f' // count: {count}' if count else '')
                for _, field, kind, count in record['fields']]
        out += ['};', f'ONDISK_SIZE({mirror}, 0x{record["size"]:02X});']
        out += [f'ONDISK_OFFSET({mirror}, {field}, 0x{offset:02X});' for offset, field, _, _ in record['fields']]
        out += [f'static_assert(alignof({mirror}) == 4 && std::is_trivially_copyable_v<{mirror}>',
                f'    && std::is_standard_layout_v<{mirror}>);']
        if 'same' in record:
            out.append(f'static_assert(sizeof({mirror}) == {record["same"]});')
        out.append('')
    out += ['} // namespace disk32', '', '// The native struct each mirror converts into, from the same field list.']
    for record in records:
        (off32, size32), (off64, size64) = layout(record['fields'], 1), layout(record['fields'], 2)
        out.append(f'RUNTIME_SIZE({record["runtime"]}, 0x{size32:02X}, 0x{size64:02X});')
        out += [f'RUNTIME_OFFSET({record["runtime"]}, {field}, 0x{a:02X}, 0x{b:02X});'
                for (_, field, _, _), a, b in zip(record['fields'], off32, off64)]
    return '\n'.join(out) + '\n'


def main():
    if len(sys.argv) != 3:
        sys.exit('usage: gen_disk32.py <schema> <output header>')
    schema, output = Path(sys.argv[1]), Path(sys.argv[2])
    records = parse(schema)
    if not records:
        fail(schema, 'no records')
    for record in records:
        offsets, size = layout(record['fields'], 1)
        declared = [field[0] for field in record['fields']]
        if offsets != declared or size != record['size']:
            fail(record['where'], f'{record["name"]}: declared offsets {declared} and size {record["size"]} '
                                  f'break the ILP32 layout {offsets} / {size}')
    text = emit(records, schema.name)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text() != text:
        output.write_text(text)


if __name__ == '__main__':
    main()
